---
collections:
  - name: community.docker
    version: 4.7.0
roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.docker
    version: 7.6.0
  - name: geerlingguy.pip
    version: 3.1.0
