---
collections:
  - name: community.docker
    version: 3.4.11
roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.docker
    version: 6.0.2
  - name: geerlingguy.pip
    version: 2.2.0
